return {
  kind = {
    Codeium = "",
    Copilot = "",
    TabNine = "󰏚",

    Class = "󰠱",
    Color = "󰏘",
    Constant = "󰏿",
    Constructor = "",
    Enum = "",
    EnumMember = "",
    Event = "",
    Field = "",
    File = "󰈙",
    Folder = "󰉋",
    Function = "󰊕",
    Interface = "",
    Keyword = "󰌋",
    Method = "",
    Module = "󰆧",
    Operator = "󰆕",
    Property = "󰜢",
    Reference = "",
    Snippet = "",
    Text = "",
    TypeParameter = "󰗴",
    Unit = "",
    Value = "󰎠",

    Array = "",
    Boolean = "",
    Collapsed = "",
    Control = "",
    Key = "󰌋",
    Namespace = "󰦮",
    Null = "",
    Number = "󰎠",
    Object = "",
    Package = "",
    String = "",
    Struct = "󰆼",
    Variable = "󰀫",
  },
  git = {
    LineAdded = "",
    LineModified = "",
    LineRemoved = "",
    LineLeft = "▎",
    LineMiddle = "│",
  },
  ui = {
    Search = "",
    Selected = "❯",
    Pointer = "➜",
    Bug = "",
    Circle = "",
    Round = "",
    Ellipsis = "",
    Plus = "",
    Robot = "󰚩",
    LSP = "",
    Fold = "",
    ThinSpace = " ",
  },
  task = {
    Canceled = " ",
    Failure = " ",
    Success = " ",
    Running = " ",
  },
  diagnostics = {
    Error = " ",
    Warning = " ",
    Info = " ",
    Hint = " ",
  },
  spinner = { "", "", "", "", "", "", "", "", "", "", "", "", "" },
  dap = {
    Stopped = { " ", "DiagnosticWarn", "DapStoppedLine" },
    Breakpoint = " ",
    BreakpointCondition = " ",
    BreakpointRejected = { " ", "DiagnosticError" },
    LogPoint = "󰮔 ",
  },
}
