return {
  kind = {
    Class = "󰠱",
    Codeium = "",
    Color = "󰏘",
    Constant = "󰏿",
    Constructor = "",
    Copilot = "",
    Enum = "",
    EnumMember = "",
    Event = "",
    Field = "󰇽",
    File = "󰈙",
    Folder = "󰉋",
    Function = "󰊕",
    Interface = "",
    Keyword = "󰌋",
    Method = "",
    Module = "󰆧",
    Operator = "󰆕",
    Property = "󰜢",
    Reference = "",
    Snippet = "",
    Text = "",
    TypeParameter = "󰅲",
    Unit = "",
    Value = "󰎠",

    Array = "",
    Boolean = "",
    Collapsed = "",
    Control = "",
    Key = "",
    Namespace = "󰦮",
    Null = "",
    Number = "󰎠",
    Object = "",
    Package = "",
    String = "",
    Struct = "󰆼",
    TabNine = "󰏚",
    Variable = "󰀫",
  },
  git = {
    LineAdded = "",
    LineModified = "",
    LineRemoved = "",
    LineLeft = "▎",
    LineMiddle = "│",
  },
  ui = {
    Search = "",
    Selected = "❯",
    Bug = "",
    Circle = "",
    Round = "",
    Ellipsis = "",
    Plus = "",
    Robot = "󰚩",
    LSP = "",
    Fold = "",
  },
  diagnostics = {
    BoldError = "",
    Error = "",
    BoldWarning = "",
    Warning = "󰗖",
    BoldInformation = "",
    Information = "",
    BoldHint = "󰟃",
    Hint = "",
  },
  spinner = { "", "", "", "", "", "", "", "", "", "", "", "", "" },
  dap = {
    Stopped = { " ", "DiagnosticWarn", "DapStoppedLine" },
    Breakpoint = " ",
    BreakpointCondition = " ",
    BreakpointRejected = { " ", "DiagnosticError" },
    LogPoint = "󰮔 ",
  },
}
